sudo: required
services:
  - docker

before_install:
  - docker build -t dgurney/docker-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dgurney/docker-client npm test

after_success:
  - docker build -t dgurney/docker-complex-client ./client
  - docker build -t dgurney/docker-complex-nginx ./nginx
  - docker build -t dgurney/docker-complex-server ./server
  - docker build -t dgurney/docker-complex-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push dgurney/docker-complex-client
  - docker push dgurney/docker-complex-nginx
  - docker push dgurney/docker-complex-server
  - docker push dgurney/docker-complex-worker